### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by iUltimateLP** [AndrewScheidecker/BrickGame#17]
Hey, I thought how Multiplayer support works with the BrickGrid. I mean, what parts need to be replicated in order to get a multiplayer result, where both server and client can place / destroy blocks, use flashlight, sky updates, etc.?

**Comment by AndrewScheidecker** [comment]
I'm not sure how to replicate the flashlight and sky light updates, since I've never done blueprint replication. That should be relatively easy, though.

Replicating the bricks is more complicated:
* You'd likely want to compress the data before replication, as it's currently quite large. Simple run-length-encoding would get you a lot, as well as only sending as many bits as are needed for the number of materials. Using Morton order for the bricks would probably give the RLE more leverage, though it might be more complexity than it's worth.
* You'd need to have some logic similar to how the BrickGridComponent shows BrickRenderComponents within some radius, but instead of showing BrickRenderComponents, it would be replicating nearby regions to clients.
* You'd also want to distinguish between replicating a whole region when a client first sees it, and replicating a smaller chunk when it's modified by some other player.
* Finally, you need a way to simulate brick changes locally, so that when a player places/destroys bricks it doesn't have to wait for a round trip to the server before displaying the result.

**Comment by iUltimateLP** [comment]
I already did flashlight and sun, but the brick stuff is too complicated for me I think, as it uses C++ (at least I think so) and I'm not really familiar with this topic. I thought so:
Every client has its own brick grid, and if somebody places a block, that will be replicated to all clients and there will be a block placed aswell, but I don't know how this will work.. If that's much C++ stuff, could you help me a bit with those compressing / decompressing?

**Comment by DefinitlyEvil** [comment]
For networking, you may wanna use Raknet(just a suggestion xD).

**Comment by iUltimateLP** [comment]
I had a look in RakNet and it's a nice library, but in which points is this better than the standard Unreal networking features it alrwady has?

**Comment by DefinitlyEvil** [comment]
I prefer 3rd-party libraries because they are more customizable. xD

**Comment by iUltimateLP** [comment]
I see they have replication of actors.. Is it hard to make it compatible to UE4? They have a link in their Readme.md about Unreal, but I can't access UDN..

**Comment by DefinitlyEvil** [comment]
@iUltimateLP Since UE is using C++ so technically you can integrate anything into it. xD
